import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import "./styles/font-awesome-all.css";
import "./styles/flaticon.css";
import "./styles/owl.css";
import "./styles/bootstrap.css";
import "./styles/jquery.fancybox.min.css";
import "./styles/animate.css";
import "./styles/jquery-ui.css";
import "./styles/nice-select.css";
import "./styles/theme-color.css";
import "./styles/style.css";
import "./styles/responsive.css";
import Loader from "@/components/Loader";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
